# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Deploy backend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./pantry_pal_backend
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v -o app

    - name: Test
      run: go test -v
    
    - name: SFTP Deploy
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        username: ${{ secrets.SSH_USERNAME }}
        server: ${{ secrets.SSH_SERVER }}
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        local_path: ./pantry_pal_backend/app
        remote_path: pantry-pal/pantry_pal_backend/

    - name: Start Server
      uses: appleboy/ssh-action@v0.1.6
      timeout-minutes: 1
      env:
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_NAME: ${{ secrets.DB_NAME }}
      with:
        host: ${{ secrets.SSH_SERVER }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        envs: DB_USERNAME,DB_PASSWORD,DB_HOST,DB_PORT,DB_NAME
        script: |
          export DB_USERNAME=$DB_USERNAME
          export DB_PASSWORD=$DB_PASSWORD
          export DB_HOST=$DB_HOST
          export DB_PORT=$DB_PORT
          export DB_NAME=$DB_NAME
          export GOOGLE_APPLICATION_CREDENTIALS=firebase-admin-sdk.json
          cd pantry-pal/pantry_pal_backend
          pm2 delete app 2> /dev/null || true && pm2 start app --name "app"
